image: netanelgilad/yoshi-ci:node10

variables:
  YOSHI_CI: 1
  NPM_CONFIG_AUDIT: "false"
  NPM_CONFIG_CACHE: ".npm-cache"

stages:
  - build
  - test

print-env:
  stage: build
  script: env

.use-node-modules-cache:
  before_script:
    - npm install --unsafe-perm
  cache:
    key: node_modules-${CI_COMMIT_REF_SLUG}
    paths:
      - ".npm-cache/"
      - node_modules/
      - packages/babel-plugin-transform-hmr-runtime/node_modules
      - packages/babel-preset-yoshi/node_modules/
      - packages/bootstrap-hot-loader/node_modules/
      - packages/create-yoshi-app/node_modules/
      - packages/eslint-config-yoshi/node_modules/
      - packages/eslint-config-yoshi-base/node_modules/
      - packages/jest-environment-yoshi-bootstrap/node_modules/
      - packages/jest-environment-yoshi-puppeteer/node_modules/
      - packages/jest-yoshi-preset/node_modules/
      - packages/tslint-config-yoshi/node_modules/
      - packages/tslint-config-yoshi-base/node_modules/
      - packages/yoshi/node_modules/
      - packages/yoshi-angular-dependencies/node_modules/
      - packages/yoshi-config/node_modules/
      - packages/yoshi-helpers/node_modules/
      - packages/yoshi-style-dependencies/node_modules/
    policy: pull

install:
  stage: build
  script: npm install --unsafe-perm
  cache:
    key: node_modules-${CI_COMMIT_REF_SLUG}
    paths:
      - ".npm-cache/"
      - node_modules/
      - packages/babel-plugin-transform-hmr-runtime/node_modules
      - packages/babel-preset-yoshi/node_modules/
      - packages/bootstrap-hot-loader/node_modules/
      - packages/create-yoshi-app/node_modules/
      - packages/eslint-config-yoshi/node_modules/
      - packages/eslint-config-yoshi-base/node_modules/
      - packages/jest-environment-yoshi-bootstrap/node_modules/
      - packages/jest-environment-yoshi-puppeteer/node_modules/
      - packages/jest-yoshi-preset/node_modules/
      - packages/tslint-config-yoshi/node_modules/
      - packages/tslint-config-yoshi-base/node_modules/
      - packages/yoshi/node_modules/
      - packages/yoshi-angular-dependencies/node_modules/
      - packages/yoshi-config/node_modules/
      - packages/yoshi-helpers/node_modules/
      - packages/yoshi-style-dependencies/node_modules/

unit:
  extends: .use-node-modules-cache
  stage: test
  script: npm run test:unit

lint:
  extends: .use-node-modules-cache
  stage: test
  before_script:
    - ls -ltr
  script: npm run lint

integration:
  extends: .use-node-modules-cache
  stage: test
  script: npm run test:integration

app-flow:
  extends: .use-node-modules-cache
  stage: test
  script: npm run test:app-flow

templates-client:
  extends: .use-node-modules-cache
  tags:
    - private
  stage: test
  script: npm run test:templates -- client

templates-client-typescript:
  extends: .use-node-modules-cache
  tags:
    - private
  stage: test
  script: npm run test:templates -- client-typescript

templates-fullstack:
  extends: .use-node-modules-cache
  tags:
    - private
  stage: test
  script: npm run test:templates -- fullstack

templates-fullstack-typescript:
  extends: .use-node-modules-cache
  tags:
    - private
  stage: test
  script: npm run test:templates -- fullstack-typescript

templates-business-manager-module:
  extends: .use-node-modules-cache
  tags:
    - private
  stage: test
  script: npm run test:templates -- business-manager-module

templates-business-manager-module-typescript:
  extends: .use-node-modules-cache
  tags:
    - private
  stage: test
  script: npm run test:templates -- business-manager-module-typescript

templates-server:
  extends: .use-node-modules-cache
  tags:
    - private
  stage: test
  script: npm run test:templates -- server

templates-server-typescript:
  extends: .use-node-modules-cache
  tags:
    - private
  stage: test
  script: npm run test:templates -- server-typescript
