language: node_js

sudo: required

os:
  - linux
  - osx

node_js:
  - 10

dist: trusty

addons:
  chrome: stable
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

install: npm i

cache:
  yarn: true
  npm: true

script:
  - 'if [ $TEST_SUITE = "lint" ]; then npm run lint; fi'
  - 'if [ $TEST_SUITE = "test:app-flow" ]; then npm run test:app-flow; fi'
  - 'if [ $TEST_SUITE = "test:unit" ]; then npm run test:unit; fi'
  - 'if [ $TEST_SUITE = "test:integration" ]; then npm run test:integration; fi'

env:
  matrix:
    - TEST_SUITE=test:app-flow

matrix:
  include:
    - os: linux
      node_js: 10
      env: TEST_SUITE="lint"
    - os: linux
      node_js: 10
      env: TEST_SUITE="test:unit"
    - os: linux
      node_js: 10
      env: TEST_SUITE="test:integration"
