language: node_js

sudo: required

os:
  - linux
  - osx

node_js:
  - 10

dist: trusty

addons:
  chrome: stable
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

install: npm i

cache:
  yarn: true
  npm: true

before_script:
  - "sysctl kernel.unprivileged_userns_clone=1"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - 'if [ $TEST_SUITE = "lint" ]; then npm run lint; fi'
  - 'if [ $TEST_SUITE = "test:app-flow" ]; then npm run test:app-flow; fi'
  - 'if [ $TEST_SUITE = "test:unit" ]; then npm run test:unit; fi'
  - 'if [ $TEST_SUITE = "test:integration" ]; then npm run test:integration; fi'
  - 'if [[ $TEST_SUITE = "website" ]] && [[ $TRAVIS_PULL_REQUEST = "false" ]] && [[ $TRAVIS_BRANCH = "master" ]]; then ./scripts/deployWebsite.sh; fi'
  - 'if [[ $TEST_SUITE = "website" ]] && [[ $TRAVIS_PULL_REQUEST != "false" ]]; then ./scripts/deployWebsitePreview.sh; fi'

env:
  matrix:
    - TEST_SUITE=test:app-flow

matrix:
  include:
    - os: linux
      node_js: 10
      env: TEST_SUITE="lint"
    - os: linux
      node_js: 10
      env: TEST_SUITE="test:unit"
    - os: linux
      node_js: 10
      env: TEST_SUITE="test:integration"
    - os: linux
      node_js: 10
      env: TEST_SUITE="website"
