language: node_js
sudo: required
node_js:
  - '10'
dist: trusty
addons:
  chrome: stable
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
install: true
cache:
  yarn: true
jobs:
  include:
    - name: "website"
      if: type != pull_request AND branch = master
      script:
      - git config --global user.name "${GH_NAME}"
      - git config --global user.email "${GH_EMAIL}"
      - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
      - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
    - name: "website - release to surge"
      if: type = pull_request
      script:
      - cd website
      - yarn install
      - yarn build
    - name: "test:integration"
      before_script:
        # Puppeteer setup
        - "sysctl kernel.unprivileged_userns_clone=1"
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        # Install
        - npm install
      script: npm run test:integration
    - name: "test:unit"
      before_script: npm install
      script: npm run test:unit
    - name: "test:app-flow"
      before_script: npm install
      script: npm run test:app-flow
    - name: "lint"
      before_script: npm install
      script: npm run lint
after_success:
  - npx surge --project ./build --domain wix-yoshi-${TRAVIS_PULL_REQUEST}.surge.sh
