language: node_js
node_js:
  - '12'
dist: trusty
install: true
cache:
  yarn: true
env:
  - WEBSITE_CHANGED = git diff --name-only $TRAVIS_COMMIT_RANGE | grep -E "website/|docs/"
jobs:
  include:
    - name: "website:publish"
      if: type != pull_request AND branch = master
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - yarn --cwd './website' && GIT_USER="${GH_NAME}" yarn --cwd './website' run publish-gh-pages