language: node_js
node_js:
  - '8'
install: true
branches:
  only:
    - master
cache:
  yarn: true
jobs:
  include:
    - script:
      - git config --global user.name "${GH_NAME}"
      - git config --global user.email "${GH_EMAIL}"
      - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
      - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
      name: "website"
    - script: npm run test:integration
      name: "test:integration"
    - script: npm run test:unit
      name: "test:unit"
    - script: npm run test:app-flow
      name: "test:app-flow"
    - script: npm run lint
      name: "lint"
