language: node_js

sudo: required

os:
  - linux
  - osx

node_js:
  - 10

dist: trusty

addons:
  chrome: stable
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

install: npm i

cache:
  yarn: true
  npm: true

script:
  - 'if [ $TEST_SUITE = "lint" ]; then npm run lint; fi'
  - 'if [ $TEST_SUITE = "test:app-flow" ]; then npm run test:app-flow; fi'
  - 'if [ $TEST_SUITE = "test:unit" ]; then npm run test:unit; fi'
  - 'if [ $TEST_SUITE = "test:integration" ]; then npm run test:integration; fi'
  - |
    if [ $TEST_SUITE = "website" AND $TRAVIS_PULL_REQUEST = "false" AND $TRAVIS_BRANCH = "master" ]; then
      git config --global user.name "${GH_NAME}"
      git config --global user.email "${GH_EMAIL}"
      echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
      cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
     fi
  - |
    if [ $TEST_SUITE = "website" AND $TRAVIS_PULL_REQUEST != "false" ]; then
      cd website
      yarn install
      yarn build
      npx surge --project ./build --domain wix-yoshi-${TRAVIS_PULL_REQUEST}.surge.sh
    fi

env:
  matrix:
    - TEST_SUITE=test:app-flow

matrix:
  include:
    - os: linux
      node_js: 10
      env: TEST_SUITE="lint"
    - os: linux
      node_js: 10
      env: TEST_SUITE="test:unit"
    - os: linux
      node_js: 10
      env: TEST_SUITE="test:integration"
    - os: linux
      node_js: 10
      env: TEST_SUITE="website"
