apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-sa
  namespace: fed-infra
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gitlab-role
  namespace: fed-infra
rules:
- apiGroups: [""]
  resources: ["secrets", "pods", "pods/exec"]
  verbs: ["get", "list", "create", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gitlab-rb
  namespace: fed-infra
subjects:
  - kind: ServiceAccount
    name: gitlab-sa
    namespace: fed-infra
roleRef:
  kind: Role
  name: gitlab-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
  namespace: fed-infra
  annotations:
    kubernetes.io/service-account.name: gitlab-sa
type: kubernetes.io/service-account-token
